name: Paintball
version: Beta_3
description: Paintball Minigame
author: Synapz_
main: me.synapz.paintball.Paintball
website: NotAdded2bukkit.yet/sorry
softdepend: [TitleAPI]

commands:
   paintball:
      description: Open the Paintbal command menu.
      aliases: [pb]