SQL:
  enabled: false
  host: localhost
  username: admin
  password: password
  database: Paintball
Bungee:
  enabled: false
  ##Found in bungee.yml on the bungee server, used to transfer players
  bungeeID: null
  serverid: Generate