name: Paintball
version: Beta_1
description: Paintball Minigame.
author: Synapz_
main: me.synapz.paint.PaintBall
database: false

commands:
   paintball:
      description: Open the Paintbal command menu.