name: Paintball
version: Beta_3
description: Paintball Minigame.
author: Synapz_
main: me.synapz.paintball.Paintball
database: false
website: NotAdded2bukkit.yet/sorry

commands:
   paintball:
      description: Open the Paintbal command menu.
      aliases: [pb]
