name: PaintBall
version: Beta_1
description: PaintBall Minigame.
author: Synapz_
main: me.synapz.paint.PaintBall
database: false

commands:
   paintball:
      description: Open the PaintBall command menu.