name: Paintball
version: Beta_1
description: Paintball Minigame.
author: Synapz_
main: me.synapz.paintball.Paintball
database: false

commands:
   paintball:
      description: Open the Paintbal command menu.
      aliases: [pb]